
server:
  port: 8082
  #context-path: /

spring:
  application:
    name: base-provider

eureka:
   instance:
     #使用ip进行注册
     prefer-ip-address: true
   client:
     service-url:
        #注册地址
        defaultZone: http://localhost:5060/eureka/

zuul:
  routes:
    base-provider:
       path: /base/**
       serviceId: base-provider
    base-test:
       path: /test/**
       serviceId: base-provider
